# Generated by Django 5.1.2 on 2026-02-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('client_type', models.CharField(choices=[('station', 'Station'), ('industriel', 'Industriel'), ('depot', 'Dépôt'), ('autre', 'Autre')], max_length=30)),
                ('nif', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=80)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('site_type', models.CharField(choices=[('depot', 'Dépôt'), ('agency', 'Agence')], max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=80)),
                ('pays', models.CharField(default='Mali', max_length=80)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tanker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adr_expires_at', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('marque', models.CharField(blank=True, max_length=60)),
                ('modele', models.CharField(blank=True, max_length=60)),
                ('capacite_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gps_device_id', models.CharField(blank=True, max_length=80)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('maintenance', 'Maintenance'), ('hors_service', 'Hors service')], default='actif', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='erp.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prenom', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('numero_permis', models.CharField(max_length=50)),
                ('permis_expire_le', models.DateField()),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_certification', models.CharField(max_length=120)),
                ('delivree_le', models.DateField()),
                ('expire_le', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='erp.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=80, unique=True)),
                ('emis_le', models.DateField()),
                ('echeance_le', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emis', 'Émis'), ('paye', 'Payé')], default='brouillon', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('raison', models.CharField(max_length=200)),
                ('emis_le', models.DateField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='erp.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paye_le', models.DateField()),
                ('methode', models.CharField(blank=True, max_length=50)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='erp.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=80)),
                ('fournisseur', models.CharField(blank=True, max_length=120)),
                ('quantite_litres', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recu_le', models.DateTimeField()),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.fueltype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.site')),
            ],
            options={
                'unique_together': {('fuel_type', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='TankerCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('capacite_litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compartiments', to='erp.tanker')),
            ],
            options={
                'unique_together': {('tanker', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='TariffRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prix_par_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_par_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('effectif_du', models.DateField()),
                ('effectif_au', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='erp.contract')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.fueltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('adresse_livraison', models.TextField()),
                ('quantite_prevue_litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifie', 'Planifié'), ('en_cours', 'En cours'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.fuelbatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.contract')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.fueltype')),
                ('site_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_depart', to='erp.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.fueltype')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='erp.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.transportorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depart_prevu', models.DateTimeField(blank=True, null=True)),
                ('arrivee_prevue', models.DateTimeField(blank=True, null=True)),
                ('depart_reel', models.DateTimeField(blank=True, null=True)),
                ('arrivee_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.driver')),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='erp.transportorder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_incident', models.CharField(max_length=120)),
                ('date_incident', models.DateTimeField()),
                ('description', models.TextField()),
                ('severite', models.CharField(choices=[('leger', 'Léger'), ('moyen', 'Moyen'), ('grave', 'Grave')], default='leger', max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='erp.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mesure_le', models.DateTimeField()),
                ('niveau_litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('capteur', 'Capteur'), ('manuel', 'Manuel')], default='capteur', max_length=20)),
                ('evenement', models.CharField(choices=[('chargement', 'Chargement'), ('dechargement', 'Déchargement'), ('en_route', 'En route')], max_length=20)),
                ('compartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.tankercompartment')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesures_carburant', to='erp.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livre_le', models.DateTimeField()),
                ('quantite_livree_litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ecart_litres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recepteur_nom', models.CharField(blank=True, max_length=120)),
                ('commentaire', models.TextField(blank=True)),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='erp.transportorder')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tanker',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='erp.vehicle'),
        ),
    ]
