# Generated by Django 5.1.2 on 2026-02-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_employee_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('taux_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_absence', models.CharField(choices=[('conge', 'Congé'), ('absence', 'Absence'), ('maladie', 'Maladie')], default='conge', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='erp.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.contributiontype')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='erp.salarypayment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
