# Generated by Django 5.1.2 on 2026-02-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_contributiontype_leaverequest_salarycontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycontribution',
            name='auto_generated',
            field=models.BooleanField(default=True),
        ),
    ]
