# Generated by Django 5.1.2 on 2026-02-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_salarycontribution_auto_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('depense_le', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
