# Generated by Django 5.1.2 on 2026-02-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_apprentice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='annee_fabrication',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assurance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='carte_grise_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/carte_grise/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motif_hors_service',
            field=models.TextField(blank=True),
        ),
    ]
