# Generated by Django 5.1.2 on 2026-02-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_vehicle_annee_fabrication_vehicle_assurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cahier_transport',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='driver',
            name='certificat_jaugeage_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/certificat_jaugeage/'),
        ),
    ]
