# Generated by Django 5.1.2 on 2026-02-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_driver_cahier_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='permis_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/permis/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cahier_transport',
            field=models.FileField(blank=True, null=True, upload_to='drivers/cahier_transport/'),
        ),
    ]
