# Generated by Django 5.1.2 on 2026-02-19 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_driver_permis_image_alter_driver_cahier_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaragePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('designation', models.CharField(max_length=160)),
                ('categorie', models.CharField(blank=True, max_length=80)),
                ('unite', models.CharField(default='piece', max_length=20)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, max_length=120)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarageServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('categorie', models.CharField(choices=[('preventif', 'Preventif'), ('correctif', 'Correctif'), ('diagnostic', 'Diagnostic'), ('carrosserie', 'Carrosserie'), ('pneumatique', 'Pneumatique')], default='preventif', max_length=30)),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('duree_standard_heures', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cout_main_oeuvre_standard', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarageWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('diagnostic', 'Diagnostic'), ('en_attente_validation', 'En attente validation'), ('planifie', 'Planifie'), ('en_cours', 'En cours'), ('controle_qualite', 'Controle qualite'), ('termine', 'Termine'), ('annule', 'Annule')], default='ouvert', max_length=30)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('ouvert_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('planifie_debut', models.DateTimeField(blank=True, null=True)),
                ('planifie_fin', models.DateTimeField(blank=True, null=True)),
                ('debut_reel', models.DateTimeField(blank=True, null=True)),
                ('fin_reel', models.DateTimeField(blank=True, null=True)),
                ('km_entree', models.PositiveIntegerField(blank=True, null=True)),
                ('km_sortie', models.PositiveIntegerField(blank=True, null=True)),
                ('panne_signalee', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('travaux_realises', models.TextField(blank=True)),
                ('cout_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('heures_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qualite_validee', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_workorders', to='erp.driver')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='erp.garageservicetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garage_workorders', to='erp.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarageWorkOrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(blank=True, max_length=120)),
                ('fichier', models.FileField(upload_to='garage/workorders/documents/')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='erp.garageworkorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
