# Generated by Django 5.1.2 on 2026-02-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_garagepart_garageservicetype_garageworkorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garageworkorder',
            name='signature_client_image',
            field=models.ImageField(blank=True, null=True, upload_to='garage/workorders/signatures/'),
        ),
        migrations.AddField(
            model_name='garageworkorder',
            name='signature_client_nom',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
